config/routes.rb
Rails.application.routes.draw do
  resources :enginerooms

  resources :inspections

  resources :visits

  resources :memberscars

end

app/models/engineroom.rb
class Engineroom < ActiveRecord::Base
  belongs_to :inspection
end

app/controllers/enginerooms_controller.rb
class EngineroomsController < ApplicationController
  before_action :set_engineroom, only: [:show, :edit, :update, :destroy]

  # GET /enginerooms
  # GET /enginerooms.json
  def index
    @enginerooms = Engineroom.all
  end

  # GET /enginerooms/1
  # GET /enginerooms/1.json
  def show
  end

  # GET /enginerooms/new
  def new
    @engineroom = Engineroom.new
  end

  # GET /enginerooms/1/edit
  def edit
  end

  # POST /enginerooms
  # POST /enginerooms.json
  def create
    @engineroom = Engineroom.new(engineroom_params)

    respond_to do |format|
      if @engineroom.save
        format.html { redirect_to @engineroom, notice: 'Engineroom was successfully created.' }
        format.json { render :show, status: :created, location: @engineroom }
      else
        format.html { render :new }
        format.json { render json: @engineroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enginerooms/1
  # PATCH/PUT /enginerooms/1.json
  def update
    respond_to do |format|
      if @engineroom.update(engineroom_params)
        format.html { redirect_to @engineroom, notice: 'Engineroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @engineroom }
      else
        format.html { render :edit }
        format.json { render json: @engineroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enginerooms/1
  # DELETE /enginerooms/1.json
  def destroy
    @engineroom.destroy
    respond_to do |format|
      format.html { redirect_to enginerooms_url, notice: 'Engineroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engineroom
      @engineroom = Engineroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engineroom_params
      params.require(:engineroom).permit(:noise_id, :oilcolor_id)
    end
end

app/helpers/enginerooms_helper.rb
module EngineroomsHelper
end

app/views/enginerooms/_form.html.erb
<%= form_for(@engineroom) do |f| %>
  <% if @engineroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@engineroom.errors.count, "error") %> prohibited this engineroom from being saved:</h2>

      <ul>
      <% @engineroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :noise_id %><br>
    <%= f.number_field :noise_id %>
  </div>
  <div class="field">
    <%= f.label :oilcolor_id %><br>
    <%= f.number_field :oilcolor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enginerooms/_show.html.erb
<p>
  <strong>Noise:</strong>
  <%= engineroom.noise_id %>
</p>

<p>
  <strong>Oilcolor:</strong>
  <%= engineroom.oilcolor_id %>
</p>

app/views/enginerooms/edit.html.erb
<h1>Editing engineroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @engineroom %> |
<%= link_to 'Back', enginerooms_path %>

app/views/enginerooms/index.html.erb
<h1>Listing enginerooms</h1>

<table>
  <thead>
    <tr>
      <th>Noise</th>
      <th>Oilcolor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enginerooms.each do |engineroom| %>
      <tr>
        <td><%= engineroom.noise_id %></td>
        <td><%= engineroom.oilcolor_id %></td>
        <td><%= link_to 'Show', engineroom %></td>
        <td><%= link_to 'Edit', edit_engineroom_path(engineroom) %></td>
        <td><%= link_to 'Destroy', engineroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Engineroom', new_engineroom_path %>

app/views/enginerooms/new.html.erb
<h1>New engineroom</h1>

<%= render 'form' %>

<%= link_to 'Back', enginerooms_path %>

app/views/enginerooms/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'show', engineroom: @engineroom %>

<%= link_to 'Edit', edit_engineroom_path(@engineroom) %> |
<%= link_to 'Back', enginerooms_path %>