config/routes.rb
Rails.application.routes.draw do
  resources :enginerooms

  resources :inspections

  resources :visits

  resources :memberscars

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :memberscar
  has_one    :inspection

  accepts_nested_attributes_for :inspection
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
    @visit.build_inspection
    @visit.inspection.build_engineroom
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:when, :gas, :odometer, :memo, :memberscar_id, inspection_attributes: [:mechanic, :memo, engineroom_attributes: [:noise_id, :oilcolor_id]])
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :when %><br>
    <%= f.datetime_select :when %>
  </div>
  <div class="field">
    <%= f.label :gas %><br>
    <%= f.number_field :gas %>
  </div>
  <div class="field">
    <%= f.label :odometer %><br>
    <%= f.number_field :odometer %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="field">
    <%= f.label :memberscar_id %><br>
    <%= f.number_field :memberscar_id %>
  </div>

  <h2>点検</h2>
  <%= f.fields_for :inspection do |inspection_fields| %>
    <div class="field">
      <%= inspection_fields.label :mechanic %><br>
      <%= inspection_fields.text_field :mechanic %>
    </div>
    <div class="field">
      <%= inspection_fields.label :memo %><br>
      <%= inspection_fields.text_area :memo %>
    </div>

    <h3>エンジンルーム点検</h3>
    <%= inspection_fields.fields_for :engineroom do |engineroom_fields| %>
      <div class="field">
        <%= engineroom_fields.label :noise_id %><br>
        <%= engineroom_fields.number_field :noise_id %>
      </div>
      <div class="field">
        <%= engineroom_fields.label :oilcolor_id %><br>
      <%= engineroom_fields.number_field :oilcolor_id %>
      </div>
    <% end %>

  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/_index.html.erb
<table>
  <thead>
    <tr>
      <th>When</th>
      <th>Gas</th>
      <th>Odometer</th>
      <th>Memo</th>
      <th>Memberscar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.when %></td>
        <td><%= visit.gas %></td>
        <td><%= visit.odometer %></td>
        <td><%= visit.memo %></td>
        <td><%= visit.memberscar_id %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<%= render 'index' %>
<br>

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<h1>来店</h1>
<p>
  <strong>When:</strong>
  <%= @visit.when %>
</p>

<p>
  <strong>Gas:</strong>
  <%= @visit.gas %>
</p>

<p>
  <strong>Odometer:</strong>
  <%= @visit.odometer %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @visit.memo %>
</p>

<p>
  <strong>Memberscar:</strong>
  <%= @visit.memberscar_id %>
</p>

<h2>点検</h2>
<%= render 'inspections/show', inspection: @visit.inspection %>

<h3>エンジンルーム</h3>
<%= render 'enginerooms/show', engineroom: @visit.inspection.engineroom %>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>