config/routes.rb
Rails.application.routes.draw do
  resources :enginerooms

  resources :inspections

  resources :visits

  resources :memberscars

end

app/models/memberscar.rb
class Memberscar < ActiveRecord::Base
  has_many :visits
end

app/controllers/memberscars_controller.rb
class MemberscarsController < ApplicationController
  before_action :set_memberscar, only: [:show, :edit, :update, :destroy]

  # GET /memberscars
  # GET /memberscars.json
  def index
    @memberscars = Memberscar.all
  end

  # GET /memberscars/1
  # GET /memberscars/1.json
  def show

    # Visit
    @visits = @memberscar.visits.all
    @visit =  @memberscar.visits.build

    # Inspection
    @inspection = @visit.inspection
    if @inspection.nil?
      @inspection = @visit.build_inspection
    end

    # Engineroom
    @engineroom = @inspection.engineroom
    if @engineroom.nil?
      @engineroom = @inspection.build_engineroom
    end

    
  end

  # GET /memberscars/new
  def new
    @memberscar = Memberscar.new
  end

  # GET /memberscars/1/edit
  def edit
  end

  # POST /memberscars
  # POST /memberscars.json
  def create
    @memberscar = Memberscar.new(memberscar_params)

    respond_to do |format|
      if @memberscar.save
        format.html { redirect_to @memberscar, notice: 'Memberscar was successfully created.' }
        format.json { render :show, status: :created, location: @memberscar }
      else
        format.html { render :new }
        format.json { render json: @memberscar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberscars/1
  # PATCH/PUT /memberscars/1.json
  def update
    respond_to do |format|
      if @memberscar.update(memberscar_params)
        format.html { redirect_to @memberscar, notice: 'Memberscar was successfully updated.' }
        format.json { render :show, status: :ok, location: @memberscar }
      else
        format.html { render :edit }
        format.json { render json: @memberscar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberscars/1
  # DELETE /memberscars/1.json
  def destroy
    @memberscar.destroy
    respond_to do |format|
      format.html { redirect_to memberscars_url, notice: 'Memberscar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memberscar
      @memberscar = Memberscar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memberscar_params
      params.require(:memberscar).permit(:numberplate, :automaker)
    end
end

app/helpers/memberscars_helper.rb
module MemberscarsHelper
end

app/views/memberscars/_form.html.erb
<%= form_for(@memberscar) do |f| %>
  <% if @memberscar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memberscar.errors.count, "error") %> prohibited this memberscar from being saved:</h2>

      <ul>
      <% @memberscar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numberplate %><br>
    <%= f.text_field :numberplate %>
  </div>
  <div class="field">
    <%= f.label :automaker %><br>
    <%= f.text_field :automaker %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberscars/edit.html.erb
<h1>Editing memberscar</h1>

<%= render 'form' %>

<%= link_to 'Show', @memberscar %> |
<%= link_to 'Back', memberscars_path %>

app/views/memberscars/index.html.erb
<h1>Listing memberscars</h1>

<table>
  <thead>
    <tr>
      <th>Numberplate</th>
      <th>Automaker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberscars.each do |memberscar| %>
      <tr>
        <td><%= memberscar.numberplate %></td>
        <td><%= memberscar.automaker %></td>
        <td><%= link_to 'Show', memberscar %></td>
        <td><%= link_to 'Edit', edit_memberscar_path(memberscar) %></td>
        <td><%= link_to 'Destroy', memberscar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memberscar', new_memberscar_path %>

app/views/memberscars/new.html.erb
<h1>New memberscar</h1>

<%= render 'form' %>

<%= link_to 'Back', memberscars_path %>

app/views/memberscars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numberplate:</strong>
  <%= @memberscar.numberplate %>
</p>

<p>
  <strong>Automaker:</strong>
  <%= @memberscar.automaker %>
</p>

<hr>
<h3>来店履歴</h3>
<%= render 'visits/index' %>

<hr>
<h3>今回の来店情報</h3>
<%= render 'visits/form' %>


<%= link_to 'Edit', edit_memberscar_path(@memberscar) %> |
<%= link_to 'Back', memberscars_path %>