config/routes.rb
Rails.application.routes.draw do
  resources :enginerooms

  resources :inspections

  resources :visits

  resources :memberscars

end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
  belongs_to :visit
  has_one    :engineroom

  accepts_nested_attributes_for :engineroom
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_action :set_inspection, only: [:show, :edit, :update, :destroy]

  # GET /inspections
  # GET /inspections.json
  def index
    @inspections = Inspection.all
  end

  # GET /inspections/1
  # GET /inspections/1.json
  def show
  end

  # GET /inspections/new
  def new
    @inspection = Inspection.new
    @engineroom = @inspection.build_engineroom
  end

  # GET /inspections/1/edit
  def edit
  end

  # POST /inspections
  # POST /inspections.json
  def create
    @inspection = Inspection.new(inspection_params)

    respond_to do |format|
      if @inspection.save
        format.html { redirect_to @inspection, notice: 'Inspection was successfully created.' }
        format.json { render :show, status: :created, location: @inspection }
      else
        format.html { render :new }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inspections/1
  # PATCH/PUT /inspections/1.json
  def update
    respond_to do |format|
      if @inspection.update(inspection_params)
        format.html { redirect_to @inspection, notice: 'Inspection was successfully updated.' }
        format.json { render :show, status: :ok, location: @inspection }
      else
        format.html { render :edit }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspections/1
  # DELETE /inspections/1.json
  def destroy
    @inspection.destroy
    respond_to do |format|
      format.html { redirect_to inspections_url, notice: 'Inspection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inspection
      @inspection = Inspection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inspection_params
      params.require(:inspection).permit(:mechanic, :memo, :visit_id, engineroom_attributes: [:noise_id, :oilcolor_id] )
    end
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/views/inspections/_form.html.erb
<%= form_for(@inspection) do |f| %>
  <% if @inspection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inspection.errors.count, "error") %> prohibited this inspection from being saved:</h2>

      <ul>
      <% @inspection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mechanic %><br>
    <%= f.text_field :mechanic %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="field">
    <%= f.label :visit_id %><br>
    <%= f.number_field :visit_id %>
  </div>

  <h2>エンジンルームの点検</h2>
  <%= f.fields_for :engineroom do |engineroom_fields| %>
    <%= engineroom_fields.number_field :noise_id %>
    <%= engineroom_fields.number_field :oilcolor_id %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inspections/_show.html.erb
<p>
  <strong>Mechanic:</strong>
  <%= inspection.mechanic %>
</p>

<p>
  <strong>Memo:</strong>
  <%= inspection.memo %>
</p>

<p>
  <strong>Visit:</strong>
  <%= inspection.visit_id %>
</p>

app/views/inspections/edit.html.erb
<h1>Editing inspection</h1>

<%= render 'form' %>

<%= link_to 'Show', @inspection %> |
<%= link_to 'Back', inspections_path %>

app/views/inspections/index.html.erb
<h1>Listing inspections</h1>

<table>
  <thead>
    <tr>
      <th>Mechanic</th>
      <th>Memo</th>
      <th>Visit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inspections.each do |inspection| %>
      <tr>
        <td><%= inspection.mechanic %></td>
        <td><%= inspection.memo %></td>
        <td><%= inspection.visit_id %></td>
        <td><%= link_to 'Show', inspection %></td>
        <td><%= link_to 'Edit', edit_inspection_path(inspection) %></td>
        <td><%= link_to 'Destroy', inspection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inspection', new_inspection_path %>

app/views/inspections/new.html.erb
<h1>New inspection</h1>

<%= render 'form' %>

<%= link_to 'Back', inspections_path %>

app/views/inspections/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'show', inspection: @inspection%>

<%= link_to 'Edit', edit_inspection_path(@inspection) %> |
<%= link_to 'Back', inspections_path %>